name: Android-Emulator
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest # Máy ảo Android chạy trên Mac cực mượt
    steps:
      - name: Chạy Android ảo
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: echo "Android dang chay roi ong oi!"
          
