name: Windows-11-Sieu-Toc
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 1. Tai Ngrok va Thiet lap
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user RunnerAdmin BlackHub123 /add
          net localgroup administrators RunnerAdmin /add
      - name: 2. Kich hoat va Chay Ngrok
        run: |
          .\ngrok\ngrok.exe authtoken "37jIpkhjZUlJ26OlOQZ9tYcd92r_brZPmcejx8Mi4SQ7BRHW"
          .\ngrok\ngrok.exe tcp --region ap 3389
          
