name: Windows-11-Sieu-Toc
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 1. Tai Ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
      - name: 2. Mo RDP va Dat Pass
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user RunnerAdmin BlackHub123 /add
          net localgroup administrators RunnerAdmin /add
      - name: 3. Chay Token cua Ong
        run: |
          .\ngrok\ngrok.exe authtoken "37jIpkhjZUlJ26OlOQZ9tYcd92r_brZPmcejx8Mi4SQ7BRHW"
          Start-Process .\ngrok\ngrok.exe -ArgumentList "tcp --region ap 3389"
      - name: 4. Doi ket noi
        run: |
          echo "DANG CHO KET NOI..."
          sleep 21600
          
